name       : eog-plugins
version    : '42.2'
release    : 24
source     :
    - https://download.gnome.org/sources/eog-plugins/42/eog-plugins-42.2.tar.xz : 604c6b57c72a680a62837dd735223be6e7b79e47cf75c92af9d12048db72918b
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libpeas-1.0)
rundeps    :
    - eog
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
