name       : eog-plugins
version    : 3.26.7
release    : 21
source     :
    - https://download.gnome.org/sources/eog-plugins/3.26/eog-plugins-3.26.7.tar.xz : 2ce6c19e29eb723e2362a8b0d9c396e686d065e17acfc584cc8c2b0949a17b3d
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
rundeps    :
    - eog
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
