name       : eog-plugins
version    : 3.16.4
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/eog-plugins/3.16/eog-plugins-3.16.4.tar.xz : 4fcfe7df19cdf8e39f5fec599d7ff46bbd82842d49083274740fbbc51cf4d25e
license    : GPL-2.0
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpeas-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
