name       : eog-plugins
version    : 3.26.1
release    : 10
source     :
    - https://download.gnome.org/sources/eog-plugins/3.26/eog-plugins-3.26.1.tar.xz : a73d0dc7a9190781f65d3132e0b1e13b666e13a1591a7cf97c1e9835aa70856c
license    : GPL-2.0
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
