name       : eog-plugins
version    : '44.0'
release    : 26
source     :
    - https://download.gnome.org/sources/eog-plugins/44/eog-plugins-44.0.tar.xz : db31cbf7bb9652db0a87113e9b51f4df2586763a261b0cbf04327d82cb38b047
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libpeas-1.0)
rundeps    :
    - eog
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
