name       : eog-plugins
version    : '42.0'
release    : 22
source     :
    - https://download.gnome.org/sources/eog-plugins/42/eog-plugins-42.0.tar.xz : 3461572401b023d1fc1b07c4baf4240c64d81947ff8b62e02d35968405927caa
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libpeas-1.0)
rundeps    :
    - eog
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
