name       : eog-plugins
version    : 3.16.1
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/eog-plugins/3.16/eog-plugins-3.16.1.tar.xz : c586b6708064dcd03612f9373a6160214b2fa4797bf8c07db530b18eda4074d9
license    : GPL-2.0
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(eog)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
