name       : eog-plugins
version    : 3.16.5
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/eog-plugins/3.16/eog-plugins-3.16.5.tar.xz : 9de42235cc7dabc4e4b228c1a27ead4ee386cf5a3cc75fdb7ea12355d408108a
license    : GPL-2.0
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
