name       : eog-plugins
version    : '42.1'
release    : 23
source     :
    - https://download.gnome.org/sources/eog-plugins/42/eog-plugins-42.1.tar.xz : 8b7211ca145a57fd5a929afd07905de742fd150743aaa2f600d718e832ad3e5f
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libpeas-1.0)
rundeps    :
    - eog
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
