name       : eog-plugins
version    : 3.26.3
release    : 13
source     :
    - https://download.gnome.org/sources/eog-plugins/3.26/eog-plugins-3.26.3.tar.xz : e385281649e7ef9e38005a73ffd5688769233a2bc8fc03e62e4da1708596d619
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
