name       : eog-plugins
version    : 3.26.4
release    : 15
source     :
    - https://download.gnome.org/sources/eog-plugins/3.26/eog-plugins-3.26.4.tar.xz : dd5a4f537d56d30e25931d32865abf684eac69362ce8320941c547461476a75d
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Eye of Gnome Plugins
description: |
    Eye of Gnome Plugins
builddeps  :
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(eog)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-1.0)
rundeps    :
    - eog
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
